export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENT = 'INIT_INGREDIENT';
export const INIT_INGREDIENT_FAILED = 'INIT_INGREDIENT_FAILED';
export const PURCHASEB_BURGER_SUCCESS = 'PURCHASEB_BURGER_SUCCESS';
export const PURCHASEB_BURGER_FAILED = 'PURCHASEB_BURGER_FAILED';
export const PURCHASEB_BURGER_Start = 'PURCHASEB_BURGER_Start';

export const PURCHASEB_INIT = 'PURCHASEB_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';